language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      node_js: "12" # to be removed on "April 2022"
    - os: osx
      node_js: "14" # to be removed on "April 2023"
    - os: linux
      dist: trusty
      sudo: required
      node_js: "14" # to be removed on "April 2023"
    - os: linux
      dist: trusty
      sudo: required
      node_js: "16" # to be removed on "April 2024"
addons:
  chrome: stable
  firefox: latest
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=google-chrome-stable; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - npm test
